services:
  database:
    image: 'postgres:16.9-bullseye'
    ports:
      - ${POSTGRES_PORT}:5432

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: America/Sao_Paulo
  test:
    build: .
    container_name: product_api_test
    command: npm run test
    working_dir: /app
    ports: 
    - "4000:9000"
    volumes:
    - ./:/app:cached
    depends_on:
    - database
